# Generated by Django 3.1.7 on 2021-03-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210313_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='risktype',
            name='fields',
            field=models.ManyToManyField(through='api.RiskTypeDefaultField', to='api.Field'),
        ),
        migrations.AlterField(
            model_name='risktypedefaultfield',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.risktype'),
        ),
    ]
