# Generated by Django 3.1.7 on 2021-03-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210313_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='fields',
            field=models.ManyToManyField(through='api.RiskField', to='api.Field'),
        ),
    ]
