# Generated by Django 3.1.7 on 2021-03-15 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_risk_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='api.risktype'),
        ),
    ]
